//! Workflow discovery and contract checking.
//!
//! Two facts about a workflow matter to gh-ship, and neither is
//! comfortably available from the API:
//!
//! 1. **Is it dispatchable?** A workflow that only declares
//!    `on: workflow_call` — what people usually mean by "reusable" —
//!    *cannot* be started by the API at all. Naming one in `ship.yml` is
//!    the single most likely setup mistake, so it is checked up front.
//!
//! 2. **Does it declare the inputs it will be dispatched with?** GitHub
//!    rejects a dispatch carrying an input the workflow does not declare,
//!    so `preview`\'s `dry_run` has to be verified before it is used.
//!
//! Both are checked by parsing the workflow YAML, because the answer has
//! to be available before anything is dispatched. Beyond these, gh-ship
//! asks nothing of a workflow: it correlates dispatch to run by ref and
//! run id, not by a nonce the workflow has to echo back.

use std::path::{Path, PathBuf};

use serde::Deserialize;

/// The correlation input gh-ship used to require.
///
/// No longer sent. Workflows generated by older versions declare it as
/// *required*, and GitHub rejects a dispatch that omits a required input, so
/// [`dispatch`](super::run::dispatch) retries with a throwaway value to keep
/// them working while `gh ship validate` flags the input as removable.
/// Remove after the next release.
pub const LEGACY_SHIP_ID_INPUT: &str = "ship_id";

/// The dispatch input that suppresses mutations, used by `preview`.
pub const DRY_RUN_INPUT: &str = "dry_run";

/// Directory holding workflow definitions.
pub const WORKFLOW_DIR: &str = ".github/workflows";

/// A workflow, as gh-ship refers to it.
///
/// Three identifiers are easy to conflate, so they are kept apart
/// deliberately:
///
/// | Concept | Example | Used for |
/// |---|---|---|
/// | **slug** | `prepare-release` | configuration and all human output |
/// | **id** | `prepare-release.yaml` | arguments passed to `gh` |
/// | **name** | `🚢 Prepare Release` | display only, never matched on |
///
/// The slug is the stable identity: a display name is free-form, may
/// carry emoji, and may be changed at any time without breaking a
/// configuration. `gh` resolves a workflow by name, filename or numeric
/// id — but *not* by stem — so the id is what actually reaches the API.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkflowRef {
    /// Filename with extension, e.g. `prepare-release.yaml`.
    pub id: String,
    /// Filename without extension, e.g. `prepare-release`.
    pub slug: String,
}

impl std::fmt::Display for WorkflowRef {
    /// Renders the slug. Everything user-facing goes through this, so a
    /// log line and an API argument cannot silently diverge.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.slug)
    }
}

impl WorkflowRef {
    /// Build a reference for a workflow gh-ship could not find on disk.
    ///
    /// The configured string is used verbatim for both, because it is
    /// all we know; `gh` may still resolve it by display name.
    pub fn unresolved(configured: &str) -> Self {
        Self {
            id: configured.to_string(),
            slug: configured.to_string(),
        }
    }
}

/// A workflow definition found on disk.
#[derive(Debug, Clone, PartialEq)]
pub struct Workflow {
    /// Path relative to the repository root.
    pub path: PathBuf,
    /// The workflow's `name:`, falling back to the file stem.
    pub name: String,
    /// Whether it declares `on: workflow_dispatch`.
    pub dispatchable: bool,
    /// Whether it declares `on: workflow_call`.
    pub callable: bool,
    /// `workflow_dispatch` input names.
    pub inputs: Vec<String>,
}

impl Workflow {
    /// The identifier to pass to `gh`.
    ///
    /// The filename is preferred over the display name: it is unique,
    /// stable, and unambiguous when two workflows share a `name:`.
    pub fn id(&self) -> String {
        self.path
            .file_name()
            .map(|f| f.to_string_lossy().into_owned())
            .unwrap_or_else(|| self.name.clone())
    }

    /// The stable identity used in configuration and in output.
    ///
    /// This is what `.github/ship.yml` refers to, so that a workflow can
    /// be renamed — or given an emoji — without breaking anything.
    pub fn slug(&self) -> String {
        self.path
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| self.name.clone())
    }

    /// Whether the display name says something the slug does not.
    ///
    /// Used to avoid printing `prepare-release (prepare-release)`.
    pub fn has_distinct_name(&self) -> bool {
        self.name != self.slug()
    }

    /// Label this workflow for a human.
    ///
    /// The slug leads because that is the identifier written to the
    /// config; the display name follows only when it adds information.
    pub fn describe(&self) -> String {
        if self.has_distinct_name() {
            format!("{}  \u{2014}  {}", self.slug(), self.name)
        } else {
            self.slug()
        }
    }

    /// This workflow as an id/slug pair.
    pub fn to_ref(&self) -> WorkflowRef {
        WorkflowRef {
            id: self.id(),
            slug: self.slug(),
        }
    }

    /// Whether it still declares the retired correlation input.
    ///
    /// Not a violation — it is harmless, just dead weight worth reporting.
    pub fn declares_legacy_ship_id(&self) -> bool {
        self.inputs.iter().any(|i| i == LEGACY_SHIP_ID_INPUT)
    }

    /// Whether it accepts the dry-run input, required by `gh ship preview`.
    pub fn accepts_dry_run(&self) -> bool {
        self.inputs.iter().any(|i| i == DRY_RUN_INPUT)
    }

    /// Every way this workflow violates the role-agnostic part of the
    /// gh-ship contract.
    ///
    /// Used where the role is not yet known — `gh ship init` weighing
    /// candidate workflows, for instance. Prefer [`Self::contract_violations_as`]
    /// once the role is settled.
    pub fn contract_violations(&self) -> Vec<Violation> {
        let mut v = Vec::new();
        if !self.dispatchable {
            v.push(Violation::NotDispatchable);
        }
        v
    }

    /// Every way this workflow violates the contract *for a given role*.
    ///
    /// `dry_run` is only meaningful for the prepare workflow: `gh ship preview`
    /// dispatches it with `dry_run=true`, and GitHub rejects a dispatch that
    /// carries an input the workflow does not declare. Catching that here
    /// turns a confusing mid-command failure into a `validate` diagnostic.
    pub fn contract_violations_as(&self, role: Role) -> Vec<Violation> {
        let mut v = self.contract_violations();
        if role == Role::Prepare && !self.accepts_dry_run() {
            v.push(Violation::MissingDryRunInput);
        }
        v
    }
}

/// The role a workflow plays in a release.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    Prepare,
    Publish,
}

impl Role {
    /// The `workflows.<key>` this role is configured under.
    pub fn key(&self) -> &'static str {
        match self {
            Self::Prepare => "prepare",
            Self::Publish => "publish",
        }
    }
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.key())
    }
}

/// A way a workflow fails to satisfy the gh-ship contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Violation {
    NotDispatchable,
    MissingDryRunInput,
}

impl Violation {
    pub fn message(&self) -> &'static str {
        match self {
            Self::NotDispatchable => "does not declare `on: workflow_dispatch`",
            Self::MissingDryRunInput => "does not declare a `dry_run` input",
        }
    }

    pub fn help(&self) -> &'static str {
        match self {
            Self::NotDispatchable => {
                "gh-ship starts workflows through the API, which can only start workflows \
                 declaring `on: workflow_dispatch`. A `workflow_call`-only workflow — what is \
                 usually called a reusable workflow — cannot be started this way. Declare both \
                 triggers to keep it reusable *and* dispatchable."
            }
            Self::MissingDryRunInput => {
                "add a boolean `dry_run` input under `workflow_dispatch.inputs` and skip pushing \
                 when it is true. `gh ship preview` dispatches with `dry_run=true`, and GitHub \
                 refuses a dispatch carrying an input the workflow does not declare."
            }
        }
    }
}

/// Minimal projection of a workflow file.
///
/// Deliberately forward-compatible: unknown keys are ignored, because a
/// workflow is the user's file and gh-ship has no business validating
/// anything beyond the handful of keys it depends on.
#[derive(Debug, Deserialize)]
struct RawWorkflow {
    #[serde(default)]
    name: Option<String>,
    // `on` is YAML 1.1's boolean `true`. serde_norway parses YAML 1.2
    // core schema so it stays a string, but we accept both spellings to
    // survive either behaviour.
    #[serde(default, rename = "on", alias = "true")]
    on: Option<serde_norway::Value>,
}

/// Parse a workflow definition.
///
/// Returns `None` when the file is not valid YAML: an unparsable
/// workflow is GitHub's problem to report, not gh-ship's.
pub fn parse(path: &Path, text: &str) -> Option<Workflow> {
    let raw: RawWorkflow = serde_norway::from_str(text).ok()?;

    let name = raw.name.clone().unwrap_or_else(|| {
        path.file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_default()
    });

    let (dispatchable, callable, inputs) = analyse_triggers(raw.on.as_ref());

    Some(Workflow {
        path: path.to_path_buf(),
        name,
        dispatchable,
        callable,
        inputs,
    })
}

/// Extract trigger facts from the `on:` value.
///
/// `on:` has three legal shapes — a bare string, a sequence of strings,
/// and a mapping — and all three appear in the wild.
fn analyse_triggers(on: Option<&serde_norway::Value>) -> (bool, bool, Vec<String>) {
    use serde_norway::Value;

    let mut dispatchable = false;
    let mut callable = false;
    let mut inputs = Vec::new();

    match on {
        Some(Value::String(s)) => {
            dispatchable = s == "workflow_dispatch";
            callable = s == "workflow_call";
        }
        Some(Value::Sequence(items)) => {
            for item in items {
                if let Value::String(s) = item {
                    dispatchable |= s == "workflow_dispatch";
                    callable |= s == "workflow_call";
                }
            }
        }
        Some(Value::Mapping(map)) => {
            for (key, value) in map {
                let Value::String(trigger) = key else {
                    continue;
                };
                match trigger.as_str() {
                    "workflow_dispatch" => {
                        dispatchable = true;
                        collect_inputs(value, &mut inputs);
                    }
                    "workflow_call" => {
                        callable = true;
                        collect_inputs(value, &mut inputs);
                    }
                    _ => {}
                }
            }
        }
        _ => {}
    }

    inputs.sort();
    inputs.dedup();
    (dispatchable, callable, inputs)
}

fn collect_inputs(trigger: &serde_norway::Value, out: &mut Vec<String>) {
    use serde_norway::Value;
    let Value::Mapping(m) = trigger else { return };
    let Some(Value::Mapping(inputs)) = m.get(Value::String("inputs".into())) else {
        return;
    };
    for key in inputs.keys() {
        if let Value::String(name) = key {
            out.push(name.clone());
        }
    }
}

/// Discover every workflow under `root/.github/workflows`.
///
/// Sorted by name for deterministic listings and stable prompts.
pub fn discover(root: &Path) -> Vec<Workflow> {
    let dir = root.join(WORKFLOW_DIR);
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return Vec::new();
    };

    let mut paths: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "yml" || x == "yaml"))
        .collect();
    paths.sort();

    let mut workflows: Vec<Workflow> = paths
        .iter()
        .filter_map(|p| {
            let text = std::fs::read_to_string(p).ok()?;
            let relative = p.strip_prefix(root).unwrap_or(p);
            parse(relative, &text)
        })
        .collect();

    // Sorted by slug, so ordering is stable and unaffected by emoji or
    // other decoration in display names.
    workflows.sort_by_key(|w| w.slug());
    workflows
}

/// Find a workflow by slug, filename, or — as a fallback — display name.
///
/// Slug wins. That matters once display names carry emoji: a config
/// should never have to spell `🚢 Prepare Release`, and renaming a
/// workflow should not break a release.
///
/// The display-name tier is kept last for compatibility with
/// configurations written before slugs were adopted.
pub fn find<'a>(workflows: &'a [Workflow], needle: &str) -> Option<&'a Workflow> {
    workflows
        .iter()
        .find(|w| w.slug() == needle)
        .or_else(|| workflows.iter().find(|w| w.id() == needle))
        .or_else(|| workflows.iter().find(|w| w.name == needle))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn wf(text: &str) -> Workflow {
        parse(Path::new(".github/workflows/prepare.yml"), text).expect("parses")
    }

    const CONFORMING: &str = r#"
name: prepare-release
on:
  workflow_dispatch:
    inputs:
      dry_run:
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      dry_run:
        required: false
        type: boolean
        default: false
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps: []
"#;

    #[test]
    fn conforming_workflow_has_no_violations() {
        let w = wf(CONFORMING);
        assert_eq!(w.name, "prepare-release");
        assert!(w.dispatchable);
        assert!(w.callable, "declaring workflow_call too keeps it reusable");
        assert!(w.accepts_dry_run());
        assert!(
            !w.declares_legacy_ship_id(),
            "a conforming workflow needs no correlation input"
        );
        assert_eq!(w.contract_violations(), vec![]);
        assert_eq!(w.id(), "prepare.yml");
    }

    #[test]
    fn call_only_workflow_is_not_dispatchable() {
        // This is *the* setup mistake: a "reusable workflow" cannot be
        // started by the API.
        let w = wf(
            "name: x\non:\n  workflow_call:\n    inputs:\n      dry_run:\n        type: boolean\n",
        );
        assert!(!w.dispatchable);
        assert!(w.callable);
        assert!(
            w.contract_violations()
                .contains(&Violation::NotDispatchable)
        );
    }

    #[test]
    fn a_bare_dispatchable_workflow_satisfies_the_contract() {
        // No `run-name`, no `ship_id`: correlation is by ref and run id now,
        // so this is all gh-ship asks of a publish workflow.
        let w = wf("name: x\non:\n  workflow_dispatch:\n");
        assert_eq!(w.contract_violations(), vec![]);
    }

    #[test]
    fn reports_a_leftover_ship_id_input() {
        let w = wf(
            "name: x\non:\n  workflow_dispatch:\n    inputs:\n      ship_id:\n        type: string\n",
        );
        assert!(w.declares_legacy_ship_id());
        assert_eq!(
            w.contract_violations(),
            vec![],
            "a leftover input is reported as removable, never as a failure"
        );
    }

    #[test]
    fn handles_bare_string_trigger() {
        let w = wf("name: x\non: workflow_dispatch\n");
        assert!(w.dispatchable);
        assert!(w.inputs.is_empty());
    }

    #[test]
    fn handles_sequence_trigger() {
        let w = wf("name: x\non: [push, workflow_dispatch]\n");
        assert!(w.dispatchable);
    }

    #[test]
    fn handles_yaml_1_1_on_parsed_as_boolean_true() {
        // Some YAML parsers turn the `on:` key into boolean `true`.
        // Whichever way it lands, the trigger analysis must work.
        let w = parse(
            Path::new("w.yml"),
            "name: x\ntrue:\n  workflow_dispatch:\n    inputs:\n      dry_run:\n        type: boolean\n",
        )
        .unwrap();
        assert!(w.dispatchable, "the `on:`/`true:` alias must be handled");
    }

    #[test]
    fn name_falls_back_to_filename() {
        let w = parse(Path::new(".github/workflows/release.yaml"), "on: push\n").unwrap();
        assert_eq!(w.name, "release");
    }

    #[test]
    fn workflow_without_triggers_is_inert() {
        let w = wf("name: x\n");
        assert!(!w.dispatchable);
        assert!(!w.callable);
    }

    #[test]
    fn invalid_yaml_is_ignored_rather_than_fatal() {
        assert!(parse(Path::new("w.yml"), "\tnot: [valid").is_none());
    }

    #[test]
    fn find_matches_slug_filename_and_name() {
        let workflows = vec![wf(CONFORMING)];
        // slug (file stem), filename, and display name all resolve.
        assert!(find(&workflows, "prepare").is_some());
        assert!(find(&workflows, "prepare.yml").is_some());
        assert!(find(&workflows, "prepare-release").is_some());
        assert!(find(&workflows, "nope").is_none());
    }

    #[test]
    fn slug_is_the_filename_without_extension() {
        let w = wf(CONFORMING);
        assert_eq!(w.slug(), "prepare");
        assert_eq!(w.id(), "prepare.yml");
        assert_eq!(w.name, "prepare-release");
    }

    /// A display name may carry emoji; the slug must stay clean, because
    /// the slug is what a configuration file has to spell.
    #[test]
    fn emoji_display_name_leaves_the_slug_alone() {
        let w = parse(
            Path::new(".github/workflows/prepare-release.yaml"),
            "name: 🚢 Prepare Release\non: workflow_dispatch\n",
        )
        .unwrap();
        assert_eq!(w.slug(), "prepare-release");
        assert_eq!(w.id(), "prepare-release.yaml");
        assert_eq!(w.name, "🚢 Prepare Release");
        assert!(w.has_distinct_name());

        let workflows = vec![w];
        assert!(
            find(&workflows, "prepare-release").is_some(),
            "a config must never have to spell the emoji name"
        );
    }

    /// Slug beats display name, so one workflow cannot hijack another's
    /// identifier by adopting it as a `name:`.
    #[test]
    fn slug_wins_over_a_colliding_display_name() {
        let decoy = parse(
            Path::new(".github/workflows/decoy.yml"),
            "name: prepare-release\non: workflow_dispatch\n",
        )
        .unwrap();
        let real = parse(
            Path::new(".github/workflows/prepare-release.yml"),
            "name: 🚢 Prepare Release\non: workflow_dispatch\n",
        )
        .unwrap();

        let workflows = vec![decoy, real];
        let found = find(&workflows, "prepare-release").expect("resolves");
        assert_eq!(
            found.id(),
            "prepare-release.yml",
            "the slug match must win over the decoy's display name"
        );
    }

    #[test]
    fn workflow_ref_displays_the_slug_but_carries_the_id() {
        let r = wf(CONFORMING).to_ref();
        assert_eq!(r.to_string(), "prepare", "output uses the slug");
        assert_eq!(r.id, "prepare.yml", "the API argument keeps the extension");
    }

    #[test]
    fn unresolved_ref_uses_the_configured_string_for_both() {
        let r = WorkflowRef::unresolved("whatever");
        assert_eq!(r.id, "whatever");
        assert_eq!(r.to_string(), "whatever");
    }

    #[test]
    fn has_distinct_name_is_false_when_name_matches_the_slug() {
        let w = parse(Path::new("release.yml"), "name: release\non: push\n").unwrap();
        assert!(!w.has_distinct_name());
    }

    #[test]
    fn discover_reads_a_directory() {
        let dir = tempfile::tempdir().unwrap();
        let wfdir = dir.path().join(WORKFLOW_DIR);
        std::fs::create_dir_all(&wfdir).unwrap();
        std::fs::write(wfdir.join("b.yml"), CONFORMING).unwrap();
        std::fs::write(wfdir.join("a.yaml"), "name: aaa\non: push\n").unwrap();
        std::fs::write(wfdir.join("README.md"), "not a workflow").unwrap();

        let found = discover(dir.path());
        assert_eq!(found.len(), 2, "non-YAML files must be ignored");
        assert_eq!(found[0].slug(), "a", "results are sorted by slug");
        assert_eq!(found[1].slug(), "b");
        assert_eq!(
            found[1].path,
            Path::new(".github/workflows/b.yml"),
            "paths are relative to the repository root"
        );
    }

    #[test]
    fn discover_on_a_repo_without_workflows_is_empty() {
        let dir = tempfile::tempdir().unwrap();
        assert!(discover(dir.path()).is_empty());
    }

    #[test]
    fn violations_explain_the_reusable_workflow_trap() {
        let help = Violation::NotDispatchable.help();
        assert!(help.contains("workflow_call"), "{help}");
        assert!(help.contains("reusable"), "{help}");
    }
}
